name: build_and_release #名称随意
on:
  push: #设置触发规则
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix: # 会分开成两个任务分别执行
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code #这部分是为了从github自动clone代码
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rename Binary
        run: |
          mv target/release/obsidian-export obsidian-export-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v2 #具体参考https://github.com/softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/') # 设置为有tag才进行上传
        with:
          # body_path: commit-message.log
          body: CICD Auto Create Release
          files: |
            LICENSE
            obsidian-export-${{ matrix.os }}
